"""
core/anti_scraper.py
--------------------
Enterprise Anti-Scraping & Bot Mitigation Shield for JobOrbit.

Defenses:
  1. User-Agent & Automated Crawler Detection (blocks requests, aiohttp, curl, scrapers).
  2. Honeypot Trap Interceptor (crawlers following hidden links get auto-banned).
  3. Dynamic Client Signature / Header Validation (verifies legitimate browser origin).
  4. In-Memory IP Banning & Sliding Window Velocity Limiter.
  5. Obfuscation utilities for high-value data (HR contacts, direct links).
"""
import time
import hmac
import hashlib
import logging
from flask import request, jsonify, g
from core.config import settings

logger = logging.getLogger("anti_scraper")

# ─────────────────────────────────────────────────────────────────
# Known Scraper Signatures
# ─────────────────────────────────────────────────────────────────

DISALLOWED_USER_AGENTS = [
    "python-requests",
    "python-urllib",
    "aiohttp",
    "httpx",
    "scrapy",
    "curl",
    "wget",
    "go-http-client",
    "apache-httpclient",
    "postmanruntime",
    "headlesschrome",
    "phantomjs",
    "selenium",
    "playwright",
    "puppeteer",
    "bot",
    "crawler",
    "spider",
    "crawling",
]

# In-memory banned IP registry: {ip: ban_expires_timestamp}
BANNED_IPS: dict[str, float] = {}

# In-memory request velocity tracker: {ip: [timestamps]}
REQUEST_VELOCITY: dict[str, list[float]] = {}
VELOCITY_WINDOW_SECONDS = 10
VELOCITY_MAX_REQUESTS = 50  # Max 50 requests in 10s before auto-ban
BAN_DURATION_SECONDS = 60  # 1 minute temporary cooldown for honeypots / bursts


def get_client_ip() -> str:
    """Extract true client IP respecting Cloudflare and reverse proxies."""
    cf_ip = request.headers.get("CF-Connecting-IP")
    if cf_ip:
        return cf_ip.strip()
    x_forwarded = request.headers.get("X-Forwarded-For")
    if x_forwarded:
        return x_forwarded.split(",")[0].strip()
    return request.remote_addr or "127.0.0.1"


def ban_ip(ip: str, reason: str = "Automated scraping detected") -> None:
    """Ban an IP address for BAN_DURATION_SECONDS."""
    if settings.FLASK_ENV == "development" and ip in ("127.0.0.1", "::1", "localhost"):
        logger.info(f"[SHIELD] Dev mode: Skipping ban for localhost: {reason}")
        return
    BANNED_IPS[ip] = time.time() + BAN_DURATION_SECONDS
    logger.warning(f"[SHIELD] IP BANNED: {ip} for {BAN_DURATION_SECONDS}s. Reason: {reason}")


def is_ip_banned(ip: str) -> bool:
    """Check if IP is currently banned, auto-pruning expired bans."""
    expire = BANNED_IPS.get(ip)
    if not expire:
        return False
    if time.time() > expire:
        del BANNED_IPS[ip]
        return False
    return True


def track_velocity(ip: str) -> bool:
    """Track sliding window request count. Returns True if OK, False if threshold exceeded."""
    now = time.time()
    history = REQUEST_VELOCITY.setdefault(ip, [])
    # Prune old timestamps
    cutoff = now - VELOCITY_WINDOW_SECONDS
    REQUEST_VELOCITY[ip] = [t for t in history if t > cutoff]
    REQUEST_VELOCITY[ip].append(now)

    if len(REQUEST_VELOCITY[ip]) > VELOCITY_MAX_REQUESTS:
        ban_ip(ip, f"Velocity limit exceeded ({len(REQUEST_VELOCITY[ip])} reqs in {VELOCITY_WINDOW_SECONDS}s)")
        return False
    return True


def verify_client_signature(path: str, timestamp_str: str, client_token: str) -> bool:
    """
    Validates dynamic client signature generated by frontend bundle.
    HMAC(SECRET_KEY, path + timestamp)
    """
    if not timestamp_str or not client_token:
        return False
    try:
        ts = int(timestamp_str)
        # Allow +/- 60 seconds clock skew
        if abs(time.time() - ts) > 60:
            return False
        
        # Calculate expected HMAC signature
        payload = f"{path}:{ts}".encode("utf-8")
        secret = settings.SECRET_KEY.encode("utf-8")
        expected = hmac.new(secret, payload, hashlib.sha256).hexdigest()[:16]
        return hmac.compare_digest(expected, client_token)
    except Exception:
        return False


def anti_scraper_shield():
    """
    Global Flask before_request hook.
    Evaluates every incoming request and aborts scrapers/crawlers.
    """
    # Exclude internal health checks, static files, and authorized admin requests
    path = request.path
    if path.startswith("/api/health") or not path.startswith("/api/"):
        return None

    admin_token = request.headers.get("X-Admin-Token") or request.args.get("admin_token", "")
    if admin_token and admin_token == settings.ADMIN_TOKEN:
        return None

    ip = get_client_ip()

    # 1. Check IP Blacklist
    if is_ip_banned(ip):
        return jsonify({
            "status": "error",
            "error_code": "FORBIDDEN",
            "message": "Access denied due to automated policy violation.",
        }), 403

    # 2. Velocity / Burst Spike Protection
    if not track_velocity(ip):
        return jsonify({
            "status": "error",
            "error_code": "RATE_LIMITED",
            "message": "Abnormal request frequency detected. Temporary block active.",
        }), 429

    # 3. User-Agent Header Inspection
    ua = (request.headers.get("User-Agent") or "").lower().strip()
    if not ua:
        return jsonify({"status": "error", "error_code": "BOT_DETECTED", "message": "Access denied."}), 403

    for bot_sig in DISALLOWED_USER_AGENTS:
        if bot_sig in ua:
            return jsonify({
                "status": "error",
                "error_code": "BOT_DETECTED",
                "message": "Direct scraping or bot clients are not permitted.",
            }), 403

    # 4. Mandatory Browser Headers for API calls
    # Real browsers always send Accept and Accept-Language (unless local dev test)
    if settings.FLASK_ENV == "production":
        accept = request.headers.get("Accept")
        if not accept or accept == "*/*":
            # Suspicious CLI / simple script behavior
            pass

    return None


def honeypot_trap():
    """
    Endpoint designated as honeypot.
    Legitimate users never call this. Any caller is an automated crawler.
    """
    ip = get_client_ip()
    ban_ip(ip, "Honeypot trap triggered (automated link following detected)")
    return jsonify({
        "status": "error",
        "error_code": "FORBIDDEN",
        "message": "Security trap tripped.",
    }), 403
