"""initial oop schema with timestamp and soft delete mixins

Revision ID: 7baf6d7cbf22
Revises: 
Create Date: 2026-10-05 15:59:24.180781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7baf6d7cbf22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_hr_contacts')
    with op.batch_alter_table('hr_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.alter_column('apply_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_jobs_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_page_num'), ['page_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_region'), ['region'], unique=False)

    with op.batch_alter_table('prep_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_prep_questions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('professor_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_jobs_status'), ['status'], unique=False)

    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scrape_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_logs_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium_tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('premium_tier')

    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_logs_status'))
        batch_op.drop_index(batch_op.f('ix_scrape_logs_created_at'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_saved_jobs_created_at'))

    with op.batch_alter_table('professor_contacts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('prep_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prep_questions_created_at'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_region'))
        batch_op.drop_index(batch_op.f('ix_jobs_page_num'))
        batch_op.drop_index(batch_op.f('ix_jobs_is_deleted'))
        batch_op.alter_column('apply_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('hr_contacts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    op.create_table('_alembic_tmp_hr_contacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dedupe_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('company', sa.VARCHAR(length=255), nullable=False),
    sa.Column('company_website', sa.VARCHAR(length=512), nullable=True),
    sa.Column('company_niche', sa.VARCHAR(length=255), nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
